// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdjDRpLIct0LtVUT1DSzfv9hk2gtjDvZA',
    appId: '1:73980620907:web:a0fcb38ba1b6414191c12e',
    messagingSenderId: '73980620907',
    projectId: 'meal-manager-app-83ad0',
    authDomain: 'meal-manager-app-83ad0.firebaseapp.com',
    storageBucket: 'meal-manager-app-83ad0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC4WW2jnDySezLh1ktYNP9jW0KCF53i0s',
    appId: '1:73980620907:android:9db848d18c04b70091c12e',
    messagingSenderId: '73980620907',
    projectId: 'meal-manager-app-83ad0',
    storageBucket: 'meal-manager-app-83ad0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGH5-awwK2rFhseOV-C5Dg8SPrD1jSyhs',
    appId: '1:73980620907:ios:8b2b58e77e9b866991c12e',
    messagingSenderId: '73980620907',
    projectId: 'meal-manager-app-83ad0',
    storageBucket: 'meal-manager-app-83ad0.firebasestorage.app',
    iosBundleId: 'com.example.mealManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGH5-awwK2rFhseOV-C5Dg8SPrD1jSyhs',
    appId: '1:73980620907:ios:8b2b58e77e9b866991c12e',
    messagingSenderId: '73980620907',
    projectId: 'meal-manager-app-83ad0',
    storageBucket: 'meal-manager-app-83ad0.firebasestorage.app',
    iosBundleId: 'com.example.mealManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdjDRpLIct0LtVUT1DSzfv9hk2gtjDvZA',
    appId: '1:73980620907:web:034c6826f4e6926a91c12e',
    messagingSenderId: '73980620907',
    projectId: 'meal-manager-app-83ad0',
    authDomain: 'meal-manager-app-83ad0.firebaseapp.com',
    storageBucket: 'meal-manager-app-83ad0.firebasestorage.app',
  );
}
